services:
  postgres:
    image: postgres:16-alpine
    container_name: postgres
    environment:
      POSTGRES_USER: jvmdreamstack
      POSTGRES_PASSWORD: password
      POSTGRES_DB: jvmdreamstack
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always
  redis:
    container_name: redis
    image: 'redis:7'
    ports:
      - '6379:6379'

volumes:
  postgres_data:
    driver: local