/*
 * This file is generated by jOOQ.
 */
package io.github.mgrzeszczak.jvmdreamstack.api.jooq


import io.github.mgrzeszczak.jvmdreamstack.api.jooq.tables.FlywaySchemaHistory
import io.github.mgrzeszczak.jvmdreamstack.api.jooq.tables.Product
import org.jooq.Catalog
import org.jooq.Table
import org.jooq.impl.SchemaImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class Public : SchemaImpl("public", DefaultCatalog.DEFAULT_CATALOG) {
    companion object {

        /**
         * The reference instance of <code>public</code>
         */
        val PUBLIC: Public = Public()
    }

    /**
     * The table <code>public.flyway_schema_history</code>.
     */
    val FLYWAY_SCHEMA_HISTORY: FlywaySchemaHistory get() = FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY

    /**
     * The table <code>public.product</code>.
     */
    val PRODUCT: Product get() = Product.PRODUCT

    override fun getCatalog(): Catalog = DefaultCatalog.DEFAULT_CATALOG

    override fun getTables(): List<Table<*>> = listOf(
        FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY,
        Product.PRODUCT
    )
}
