/*
 * This file is generated by jOOQ.
 */
package io.github.mgrzeszczak.jvmdreamstack.api.jooq.tables.records


import io.github.mgrzeszczak.jvmdreamstack.api.jooq.tables.Product

import org.jooq.Record1
import org.jooq.impl.UpdatableRecordImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class ProductRecord private constructor() : UpdatableRecordImpl<ProductRecord>(Product.PRODUCT) {

    open var id: Long?
        set(value): Unit = set(0, value)
        get(): Long? = get(0) as Long?

    open var name: String
        set(value): Unit = set(1, value)
        get(): String = get(1) as String

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    override fun key(): Record1<Long?> = super.key() as Record1<Long?>

    /**
     * Create a detached, initialised ProductRecord
     */
    constructor(id: Long? = null, name: String) : this() {
        this.id = id
        this.name = name
        resetChangedOnNotNull()
    }
}
