/*
 * This file is generated by jOOQ.
 */
package io.github.mgrzeszczak.jvmdreamstack.api.jooq.tables.references


import io.github.mgrzeszczak.jvmdreamstack.api.jooq.tables.FlywaySchemaHistory
import io.github.mgrzeszczak.jvmdreamstack.api.jooq.tables.Product


/**
 * The table <code>public.flyway_schema_history</code>.
 */
val FLYWAY_SCHEMA_HISTORY: FlywaySchemaHistory = FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY

/**
 * The table <code>public.product</code>.
 */
val PRODUCT: Product = Product.PRODUCT
